# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4663a4fcf443df5a9b7e7b2ef17bfc8ebb14fb0557e5b4f1c712d57c00912d14c4601a3413d811e29ef76b345298b6f228a035ef26f22fabd74802c7784ea18

test:
  secret_key_base: ff7094ce2e19d716b8683e96e63cc8c7594d812155b5f4676006f887aedf37bb1fddb1416b7385d4fad6ae2b9636ae6fbd131e7ce82064a2904f694218e97bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
